// generated by scripts/generate-assets.mjs — do not edit by hand

/** PLX-02 "The Crossing", 64×64 space. Rising strand passes over. */
export const crossing = {
  viewBox: '0 0 64 64',
  /** The over strand (bottom-left to top-right). */
  rising: 'M48 12 C32 22 32 42 16 52',
  /** The under strand, gap pre-cut per master. Key = stroke width. */
  descendingCut: {
    7: 'M16 12 C20.16 14.6 23.23 17.87 25.79 21.47 M38.21 42.53 C40.77 46.13 43.84 49.4 48 52',
    9: 'M16 12 C19.31 14.07 21.93 16.56 24.16 19.31 M39.84 44.69 C42.07 47.44 44.69 49.93 48 52',
    14: 'M16 12 C17.09 12.68 18.11 13.41 19.07 14.18 M44.93 49.82 C45.89 50.59 46.91 51.32 48 52',
  },
} as const;

/** The in-word ✕ crop of the crossing (wordmark use, stroke 14). */
export const wordmarkX = {
  viewBox: '9 5 46 54',
  rising: crossing.rising,
  descendingCut: crossing.descendingCut[14],
  strokeWidth: 14,
} as const;

/** The braid band (the crossing repeated), 184×64 space. */
export const band = {
  viewBox: '0 0 184 64',
  strokeWidth: 6,
  /** Over at the outer crossings. */
  accent: 'M8 22 C32 22 40 42 64 42 C71.69 42 77.74 39.94 83.2 37.15 M100.8 26.85 C106.26 24.06 112.31 22 120 22 C144 22 152 42 176 42',
  /** Over at the middle crossing. */
  ink: 'M8 42 C15.69 42 21.74 39.94 27.2 37.15 M44.8 26.85 C50.26 24.06 56.31 22 64 22 C88 22 96 42 120 42 C127.69 42 133.74 39.94 139.2 37.15 M156.8 26.85 C162.26 24.06 168.31 22 176 22',
} as const;
